- type: entity
  abstract: true
  save: false
  parent: BaseMobVulpkanin
  id: BaseMobGunsawian
  name: Urist McGunsaw
  components:
  - type: Icon
    sprite: _PV/Mobs/Species/Gunsawian/parts.rsi
    state: full
  - type: Body
    prototype: Gunsawian
  - type: HumanoidAppearance
    species: Gunsawian
    hideLayersOnEquip:
    - Snout
    - SnoutCover
    - HeadTop
    - HeadSide
    - FacialHair
    - Hair
  - type: Bloodstream
    bloodReferenceSolution:
      reagents:
      - ReagentId: GunsawianBlood
        Quantity: 300
  - type: Inventory
    speciesId: gunsawian
    displacements:
      head:
        sizeMaps:
          32:
            sprite: _PV/Mobs/Species/Gunsawian/displacement.rsi
            state: head

- type: entity
  parent: MobVulpkaninDummy
  id: MobGunsawianDummy
  categories: [ HideSpawnMenu ]
  components:
  - type: HumanoidAppearance
    species: Gunsawian
    hideLayersOnEquip:
    - Snout
    - HeadTop
    - HeadSide
  - type: Inventory
    speciesId: gunsawian
    displacements:
      head:
        sizeMaps:
          32:
            sprite: _PV/Mobs/Species/Gunsawian/displacement.rsi
            state: head
