using Content.Client.UserInterface.Controls;
using Content.Shared._PV.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._PV.Atmos;

[GenerateTypedNameReferences]
public sealed partial class VacuumPumpWindow : FancyWindow
{
    public event Action? OnTogglePressed;

    public VacuumPumpWindow()
    {
        RobustXamlLoader.Load(this);
        ToggleButton.OnPressed += _ => OnTogglePressed?.Invoke();
    }

    public void UpdateState(VacuumPumpUiState state)
    {
        ToggleButton.Text = state.Enabled ? "OFF" : "ON";
        ToggleButton.Disabled = !state.Powered;
    }
}
