using Content.Client.UserInterface.Controls;
using Content.Shared._PV.Ranching;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._PV.Ranching;

[GenerateTypedNameReferences]
public sealed partial class AnimalAnalyzerWindow : FancyWindow
{
    public AnimalAnalyzerWindow() => RobustXamlLoader.Load(this);

    public void Populate(AnimalAnalyzerUiState state)
    {
        AnimalName.Text = state.Name;
        SetMeter(FoodBar, FoodValue, state.FoodPercent);
        SetMeter(WaterBar, WaterValue, state.WaterPercent);
        LifeStage.Text = Loc.GetString("animal-analyzer-life-stage", ("stage", state.LifeStage));
        BreedingStatus.Text = Loc.GetString("animal-analyzer-breeding", ("status", state.BreedingStatus));
    }

    private static void SetMeter(Robust.Client.UserInterface.Controls.ProgressBar bar,
        Robust.Client.UserInterface.Controls.Label label, float value)
    {
        bar.Value = Math.Max(0, value);
        label.Text = value < 0 ? Loc.GetString("animal-analyzer-unknown") : $"{value:F0}%";
    }
}
